spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.skanl.kafka.ChunkResponseDeserializer
      group-id: batch-async-manager
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.skanl.kafka.ChunkRequestSerializer
  application:
    name: batch-async

mongodb:
  skanl:
    host: 127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019
    database: batch-async

primary:
  mongodb:
    uri: mongodb://${mongodb.skanl.host}/${mongodb.skanl.database}?replicaSet=rs0


server:
  port: 8080

visitor:
  filePath: classpath:/visitors.csv

security:
  basic:
    enabled: false
  ignored: /**

management:
  security:
    enabled: false
