spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  devtools:
    livereload:
      enabled: true
  application:
    name: batch-async
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/batch-async

server:
  port: 8080

visitor:
  filePath: classpath:/visitors.csv
